-- File generated by the BNF Converter (bnfc 2.9.5).

{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif

-- | Pretty-printer for Syntax.

module Syntax.Print where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified Syntax.Abs
import qualified Data.Text

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 False (map ($ "") $ d []) ""
  where
  rend
    :: Int        -- ^ Indentation level.
    -> Bool       -- ^ Pending indentation to be output before next character?
    -> [String]
    -> ShowS
  rend i p = \case
      "["      :ts -> char '[' . rend i False ts
      "("      :ts -> char '(' . rend i False ts
      "{"      :ts -> onNewLine i     p . showChar   '{'  . new (i+1) ts
      "}" : ";":ts -> onNewLine (i-1) p . showString "};" . new (i-1) ts
      "}"      :ts -> onNewLine (i-1) p . showChar   '}'  . new (i-1) ts
      [";"]        -> char ';'
      ";"      :ts -> char ';' . new i ts
      t  : ts@(s:_) | closingOrPunctuation s
                   -> pending . showString t . rend i False ts
      t        :ts -> pending . space t      . rend i False ts
      []           -> id
    where
    -- Output character after pending indentation.
    char :: Char -> ShowS
    char c = pending . showChar c

    -- Output pending indentation.
    pending :: ShowS
    pending = if p then indent i else id

  -- Indentation (spaces) for given indentation level.
  indent :: Int -> ShowS
  indent i = replicateS (2*i) (showChar ' ')

  -- Continue rendering in new line with new indentation.
  new :: Int -> [String] -> ShowS
  new j ts = showChar '\n' . rend j True ts

  -- Make sure we are on a fresh line.
  onNewLine :: Int -> Bool -> ShowS
  onNewLine i p = (if p then id else showChar '\n') . indent i

  -- Separate given string from following text by a space (if needed).
  space :: String -> ShowS
  space t s =
    case (all isSpace t, null spc, null rest) of
      (True , _   , True ) -> []             -- remove trailing space
      (False, _   , True ) -> t              -- remove trailing space
      (False, True, False) -> t ++ ' ' : s   -- add space if none
      _                    -> t ++ s
    where
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt i = concatD . map (prt i)

instance Print Char where
  prt _ c = doc (showChar '\'' . mkEsc '\'' c . showChar '\'')

instance Print String where
  prt _ = printString

printString :: String -> Doc
printString s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print Syntax.Abs.Number where
  prt _ (Syntax.Abs.Number i) = doc $ showString (Data.Text.unpack i)
instance Print Syntax.Abs.Chr where
  prt _ (Syntax.Abs.Chr i) = doc $ showString (Data.Text.unpack i)
instance Print Syntax.Abs.Str where
  prt _ (Syntax.Abs.Str i) = doc $ showString (Data.Text.unpack i)
instance Print Syntax.Abs.Hole where
  prt _ (Syntax.Abs.Hole i) = doc $ showString (Data.Text.unpack i)
instance Print Syntax.Abs.Id where
  prt _ (Syntax.Abs.Id (_,i)) = doc $ showString (Data.Text.unpack i)
instance Print Syntax.Abs.Repl where
  prt i = \case
    Syntax.Abs.LetR decs -> prPrec i 0 (concatD [doc (showString "let"), doc (showString "{"), prt 0 decs, doc (showString "}"), doc (showString ";")])
    Syntax.Abs.ExpR exp -> prPrec i 0 (concatD [prt 0 exp, doc (showString ";")])
    Syntax.Abs.RequireR str -> prPrec i 0 (concatD [doc (showString "require"), prt 0 str, doc (showString ";")])

instance Print [Syntax.Abs.Dec] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ";"), prt 0 xs]

instance Print Syntax.Abs.Dec where
  prt i = \case
    Syntax.Abs.StructureD structurekwd rule -> prPrec i 0 (concatD [prt 0 structurekwd, prt 0 rule])
    Syntax.Abs.ConstantD rule -> prPrec i 0 (concatD [prt 0 rule])
    Syntax.Abs.ProofD proofsteps -> prPrec i 0 (concatD [doc (showString "proof"), doc (showString "{"), prt 0 proofsteps, doc (showString "}"), doc (showString "qed")])
    Syntax.Abs.DeclarationD patterns -> prPrec i 0 (concatD [doc (showString "declaration"), prt 0 patterns])
    Syntax.Abs.PipeClauseD pipeclause -> prPrec i 0 (concatD [prt 0 pipeclause])

instance Print Syntax.Abs.StructureKwd where
  prt i = \case
    Syntax.Abs.DataKwd -> prPrec i 0 (concatD [doc (showString "data")])
    Syntax.Abs.RecordKwd -> prPrec i 0 (concatD [doc (showString "record")])
    Syntax.Abs.ModuleKwd -> prPrec i 0 (concatD [doc (showString "module")])
    Syntax.Abs.ClassKwd -> prPrec i 0 (concatD [doc (showString "class")])
    Syntax.Abs.InstanceKwd -> prPrec i 0 (concatD [doc (showString "instance")])
    Syntax.Abs.AxiomKwd -> prPrec i 0 (concatD [doc (showString "axiom")])
    Syntax.Abs.TheoremKwd -> prPrec i 0 (concatD [doc (showString "theorem")])

instance Print Syntax.Abs.Rule where
  prt i = \case
    Syntax.Abs.ByBlockR pat proofsteps -> prPrec i 0 (concatD [prt 0 pat, doc (showString "by"), doc (showString "{"), prt 0 proofsteps, doc (showString "}")])
    Syntax.Abs.ProofR pat proofsteps -> prPrec i 0 (concatD [prt 0 pat, doc (showString "proof"), doc (showString "{"), prt 0 proofsteps, doc (showString "}"), doc (showString "qed")])
    Syntax.Abs.ValueR pat exp -> prPrec i 0 (concatD [prt 0 pat, doc (showString "="), prt 0 exp])
    Syntax.Abs.WhereR pat decs -> prPrec i 0 (concatD [prt 0 pat, doc (showString "where"), doc (showString "{"), prt 0 decs, doc (showString "}")])
    Syntax.Abs.SigR pat -> prPrec i 0 (concatD [prt 0 pat])

instance Print [Syntax.Abs.ProofStep] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ";"), prt 0 xs]

instance Print Syntax.Abs.ProofStep where
  prt i = \case
    Syntax.Abs.ProofDecPS proofdec -> prPrec i 0 (concatD [prt 0 proofdec])
    Syntax.Abs.BulletBlockPS proofsteps -> prPrec i 0 (concatD [doc (showString "."), doc (showString "{"), prt 0 proofsteps, doc (showString "}")])
    Syntax.Abs.CasesPS exps -> prPrec i 0 (concatD [doc (showString "cases"), prt 0 exps])
    Syntax.Abs.CasesWithPS exps -> prPrec i 0 (concatD [doc (showString "cases"), prt 0 exps, doc (showString "with")])
    Syntax.Abs.InductionPS exps -> prPrec i 0 (concatD [doc (showString "induction"), prt 0 exps, doc (showString "with")])
    Syntax.Abs.PipeClausePS pipeclause -> prPrec i 0 (concatD [prt 0 pipeclause])
    Syntax.Abs.ProvingPS exp -> prPrec i 0 (concatD [doc (showString "proving"), prt 0 exp])
    Syntax.Abs.ApplyPS exp exps -> prPrec i 0 (concatD [doc (showString "apply"), prt 0 exp, doc (showString ","), prt 0 exps])
    Syntax.Abs.InstantiatePS exp -> prPrec i 0 (concatD [doc (showString "instantiate"), prt 0 exp])
    Syntax.Abs.IntroPS patterns -> prPrec i 0 (concatD [doc (showString "\\"), prt 0 patterns])
    Syntax.Abs.WitnessPS expopt -> prPrec i 0 (concatD [doc (showString "witness"), prt 0 expopt])
    Syntax.Abs.ExpPS exp -> prPrec i 0 (concatD [prt 0 exp])

instance Print Syntax.Abs.ProofDec where
  prt i = \case
    Syntax.Abs.AssumePD patterns -> prPrec i 0 (concatD [doc (showString "assume"), prt 0 patterns])
    Syntax.Abs.ByContradictionPD pat annopt -> prPrec i 0 (concatD [doc (showString "by-contradiction"), prt 11 pat, prt 0 annopt])
    Syntax.Abs.LetPD decs -> prPrec i 0 (concatD [doc (showString "let"), doc (showString "{"), prt 0 decs, doc (showString "}")])
    Syntax.Abs.LemmaPD rule -> prPrec i 0 (concatD [doc (showString "lemma"), prt 0 rule])
    Syntax.Abs.OpenPD id_ -> prPrec i 0 (concatD [doc (showString "open"), prt 0 id_])
    Syntax.Abs.PickAnyPD patterns -> prPrec i 0 (concatD [doc (showString "pick-any"), prt 0 patterns])
    Syntax.Abs.PickWitnessPD patterns exp -> prPrec i 0 (concatD [doc (showString "pick-witness"), prt 0 patterns, doc (showString "for"), prt 0 exp])
    Syntax.Abs.ChainingPD chainlinks -> prPrec i 0 (concatD [doc (showString "chaining"), doc (showString "{"), prt 0 chainlinks, doc (showString "}")])
    Syntax.Abs.RewritePD rewriteitems -> prPrec i 0 (concatD [doc (showString "rewrite"), prt 0 rewriteitems])
    Syntax.Abs.UnfoldPD pats -> prPrec i 0 (concatD [doc (showString "unfold"), prt 2 pats])

instance Print [Syntax.Abs.ChainLink] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ";"), prt 0 xs]

instance Print Syntax.Abs.ChainLink where
  prt i = \case
    Syntax.Abs.EasyCL chainop exp -> prPrec i 0 (concatD [prt 0 chainop, prt 11 exp])
    Syntax.Abs.ByCL chainop exp proofsteps -> prPrec i 0 (concatD [prt 0 chainop, prt 11 exp, doc (showString "by"), doc (showString "{"), prt 0 proofsteps, doc (showString "}")])

instance Print Syntax.Abs.ChainOp where
  prt i = \case
    Syntax.Abs.LeftLongArrowCO -> prPrec i 0 (concatD [doc (showString "<--")])
    Syntax.Abs.LeftArrowCO -> prPrec i 0 (concatD [doc (showString "<-")])
    Syntax.Abs.RightLongArrowCO -> prPrec i 0 (concatD [doc (showString "-->")])
    Syntax.Abs.RightArrowCO -> prPrec i 0 (concatD [doc (showString "->")])
    Syntax.Abs.EqCO -> prPrec i 0 (concatD [doc (showString "=")])
    Syntax.Abs.EqualCO -> prPrec i 0 (concatD [doc (showString "===")])
    Syntax.Abs.EquivCO -> prPrec i 0 (concatD [doc (showString "<-->")])
    Syntax.Abs.ExpCO exp -> prPrec i 0 (concatD [prt 11 exp])

instance Print [Syntax.Abs.RewriteItem] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print Syntax.Abs.RewriteItem where
  prt i = \case
    Syntax.Abs.MkRI directionopt exp -> prPrec i 0 (concatD [prt 0 directionopt, prt 0 exp])

instance Print Syntax.Abs.DirectionOpt where
  prt i = \case
    Syntax.Abs.LeftDO -> prPrec i 0 (concatD [doc (showString "<-")])
    Syntax.Abs.RightDO -> prPrec i 0 (concatD [doc (showString "->")])
    Syntax.Abs.NoDO -> prPrec i 0 (concatD [])

instance Print Syntax.Abs.Patterns where
  prt i = \case
    Syntax.Abs.MkP params annopt -> prPrec i 0 (concatD [prt 0 params, prt 0 annopt])

instance Print [Syntax.Abs.Param] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print Syntax.Abs.Param where
  prt i = \case
    Syntax.Abs.BareP pat -> prPrec i 0 (concatD [prt 11 pat])
    Syntax.Abs.AtP pat -> prPrec i 0 (concatD [doc (showString "@"), prt 11 pat])
    Syntax.Abs.HashP pat -> prPrec i 0 (concatD [doc (showString "#"), prt 11 pat])

instance Print [Syntax.Abs.Pat] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 2 x]
  prt _ (x:xs) = concatD [prt 2 x, doc (showString ","), prt 2 xs]

instance Print Syntax.Abs.Pat where
  prt i = \case
    Syntax.Abs.NoncomputableP pat -> prPrec i 0 (concatD [doc (showString "noncomputable"), prt 1 pat])
    Syntax.Abs.TypeP pat -> prPrec i 0 (concatD [doc (showString "type"), prt 1 pat])
    Syntax.Abs.PropP pat -> prPrec i 0 (concatD [doc (showString "proposition"), prt 1 pat])
    Syntax.Abs.CtorAnnP pat exps -> prPrec i 1 (concatD [prt 2 pat, doc (showString "of"), prt 1 exps])
    Syntax.Abs.SuperAnnP pat exps -> prPrec i 1 (concatD [prt 2 pat, doc (showString ":>"), prt 1 exps])
    Syntax.Abs.SubAnnP pat exps -> prPrec i 1 (concatD [prt 2 pat, doc (showString "<:"), prt 1 exps])
    Syntax.Abs.AnnP pat exp -> prPrec i 2 (concatD [prt 3 pat, doc (showString ":"), prt 1 exp])
    Syntax.Abs.OrP pat1 pat2 -> prPrec i 3 (concatD [prt 4 pat1, doc (showString "|"), prt 3 pat2])
    Syntax.Abs.AndP pat1 pat2 -> prPrec i 4 (concatD [prt 5 pat1, doc (showString "&"), prt 4 pat2])
    Syntax.Abs.IndP pat -> prPrec i 10 (concatD [doc (showString "ind"), prt 11 pat])
    Syntax.Abs.CallP pat param params -> prPrec i 10 (concatD [prt 11 pat, prt 0 param, prt 0 params])
    Syntax.Abs.NumberP number -> prPrec i 11 (concatD [prt 0 number])
    Syntax.Abs.CharP chr -> prPrec i 11 (concatD [prt 0 chr])
    Syntax.Abs.StringP str -> prPrec i 11 (concatD [prt 0 str])
    Syntax.Abs.HoleP hole -> prPrec i 11 (concatD [prt 0 hole])
    Syntax.Abs.VarP id_ -> prPrec i 11 (concatD [prt 0 id_])
    Syntax.Abs.RecordP fieldpats -> prPrec i 11 (concatD [doc (showString "record"), doc (showString "{"), prt 0 fieldpats, doc (showString "}")])
    Syntax.Abs.TupleP pat pats -> prPrec i 11 (concatD [doc (showString "("), prt 2 pat, doc (showString ","), prt 2 pats, doc (showString ")")])
    Syntax.Abs.UnitP -> prPrec i 11 (concatD [doc (showString "("), doc (showString ")")])
    Syntax.Abs.WitnessP pat1 pat2 -> prPrec i 11 (concatD [doc (showString "("), doc (showString "witness"), prt 0 pat1, doc (showString "such-that"), prt 0 pat2, doc (showString ")")])

instance Print [Syntax.Abs.FieldPat] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ";"), prt 0 xs]

instance Print Syntax.Abs.FieldPat where
  prt i = \case
    Syntax.Abs.PunP id_ -> prPrec i 0 (concatD [prt 0 id_])
    Syntax.Abs.FieldP id_ pat -> prPrec i 0 (concatD [prt 0 id_, doc (showString "="), prt 0 pat])

instance Print Syntax.Abs.AnnOpt where
  prt i = \case
    Syntax.Abs.HasAnn exp -> prPrec i 0 (concatD [doc (showString ":"), prt 1 exp])
    Syntax.Abs.NoAnn -> prPrec i 0 (concatD [])

instance Print Syntax.Abs.ExpOpt where
  prt i = \case
    Syntax.Abs.HasExp exp -> prPrec i 0 (concatD [prt 0 exp])
    Syntax.Abs.NoExp -> prPrec i 0 (concatD [])

instance Print [Syntax.Abs.Exp] where
  prt _ [] = concatD []
  prt 1 [x] = concatD [prt 1 x]
  prt 1 (x:xs) = concatD [prt 1 x, doc (showString "&"), prt 1 xs]
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print Syntax.Abs.Exp where
  prt i = \case
    Syntax.Abs.EqE exp1 exp2 -> prPrec i 0 (concatD [prt 1 exp1, doc (showString "="), prt 0 exp2])
    Syntax.Abs.ApplyE exp -> prPrec i 0 (concatD [doc (showString "apply"), prt 0 exp])
    Syntax.Abs.ProofDecInE proofdec exp -> prPrec i 0 (concatD [prt 0 proofdec, doc (showString "in"), prt 0 exp])
    Syntax.Abs.WitnessSuchThatE exps exp -> prPrec i 1 (concatD [doc (showString "witness"), prt 0 exps, doc (showString "such-that"), prt 1 exp])
    Syntax.Abs.AnnE exp1 exp2 -> prPrec i 1 (concatD [prt 2 exp1, doc (showString ":"), prt 1 exp2])
    Syntax.Abs.FunE params exp -> prPrec i 1 (concatD [doc (showString "\\"), prt 0 params, doc (showString "->"), prt 1 exp])
    Syntax.Abs.ProvingByE expopt proofsteps -> prPrec i 1 (concatD [doc (showString "proving"), prt 0 expopt, doc (showString "by"), doc (showString "{"), prt 0 proofsteps, doc (showString "}")])
    Syntax.Abs.SufficesByE exp proofsteps -> prPrec i 1 (concatD [doc (showString "suffices"), prt 0 exp, doc (showString "by"), doc (showString "{"), prt 0 proofsteps, doc (showString "}")])
    Syntax.Abs.ExistsE patterns exp -> prPrec i 1 (concatD [doc (showString "exists"), prt 0 patterns, doc (showString ","), prt 1 exp])
    Syntax.Abs.ForallE patterns exp -> prPrec i 1 (concatD [doc (showString "forall"), prt 0 patterns, doc (showString ","), prt 1 exp])
    Syntax.Abs.ArrowE exp1 exp2 -> prPrec i 1 (concatD [prt 2 exp1, doc (showString "->"), prt 1 exp2])
    Syntax.Abs.ImplicationE exp1 exp2 -> prPrec i 1 (concatD [prt 2 exp1, doc (showString "-->"), prt 1 exp2])
    Syntax.Abs.EquivalenceE exp1 exp2 -> prPrec i 2 (concatD [prt 3 exp1, doc (showString "<-->"), prt 3 exp2])
    Syntax.Abs.DisjunctionE exp1 exp2 -> prPrec i 3 (concatD [prt 4 exp1, doc (showString "\\/"), prt 3 exp2])
    Syntax.Abs.ConjunctionE exp1 exp2 -> prPrec i 4 (concatD [prt 5 exp1, doc (showString "/\\"), prt 4 exp2])
    Syntax.Abs.NegationE exp -> prPrec i 5 (concatD [doc (showString "~"), prt 5 exp])
    Syntax.Abs.EqualE exp1 exp2 -> prPrec i 5 (concatD [prt 6 exp1, doc (showString "==="), prt 6 exp2])
    Syntax.Abs.CallE exp args -> prPrec i 10 (concatD [prt 11 exp, prt 0 args])
    Syntax.Abs.ExplicitE id_ -> prPrec i 11 (concatD [doc (showString "@"), prt 0 id_])
    Syntax.Abs.LamCasesE patterns clauses -> prPrec i 12 (concatD [doc (showString "\\"), prt 0 patterns, doc (showString "where"), doc (showString "{"), prt 0 clauses, doc (showString "}")])
    Syntax.Abs.CaseE exp clauses -> prPrec i 12 (concatD [doc (showString "case"), prt 0 exp, doc (showString "where"), doc (showString "{"), prt 0 clauses, doc (showString "}")])
    Syntax.Abs.MatchWith exp pipeclauses -> prPrec i 12 (concatD [doc (showString "match"), prt 0 exp, doc (showString "with"), prt 0 pipeclauses])
    Syntax.Abs.InstantiateWithE exp -> prPrec i 12 (concatD [doc (showString "instantiate"), prt 0 exp, doc (showString "with")])
    Syntax.Abs.UnitE -> prPrec i 12 (concatD [doc (showString "("), doc (showString ")")])
    Syntax.Abs.TupleE exp exps -> prPrec i 12 (concatD [doc (showString "("), prt 0 exp, doc (showString ","), prt 0 exps, doc (showString ")")])
    Syntax.Abs.RecordE decs -> prPrec i 12 (concatD [doc (showString "record"), doc (showString "{"), prt 0 decs, doc (showString "}")])
    Syntax.Abs.RecordUpdateE exp decs -> prPrec i 12 (concatD [doc (showString "record"), prt 0 exp, doc (showString "where"), doc (showString "{"), prt 0 decs, doc (showString "}")])
    Syntax.Abs.AssumptionE -> prPrec i 12 (concatD [doc (showString "assumption")])
    Syntax.Abs.NumberE number -> prPrec i 12 (concatD [prt 0 number])
    Syntax.Abs.CharE chr -> prPrec i 12 (concatD [prt 0 chr])
    Syntax.Abs.StringE str -> prPrec i 12 (concatD [prt 0 str])
    Syntax.Abs.HoleE hole -> prPrec i 12 (concatD [prt 0 hole])
    Syntax.Abs.VarE id_ -> prPrec i 12 (concatD [prt 0 id_])

instance Print [Syntax.Abs.Clause] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ";"), prt 0 xs]

instance Print Syntax.Abs.Clause where
  prt i = \case
    Syntax.Abs.MkC params exp -> prPrec i 0 (concatD [prt 0 params, doc (showString "->"), prt 1 exp])

instance Print [Syntax.Abs.PipeClause] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print Syntax.Abs.PipeClause where
  prt i = \case
    Syntax.Abs.MkPC pats proofsteps -> prPrec i 0 (concatD [doc (showString "|"), prt 2 pats, doc (showString "=>"), doc (showString "{"), prt 0 proofsteps, doc (showString "}")])

instance Print [Syntax.Abs.Arg] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print Syntax.Abs.Arg where
  prt i = \case
    Syntax.Abs.BareA exp -> prPrec i 0 (concatD [prt 12 exp])
    Syntax.Abs.AtA exp -> prPrec i 0 (concatD [doc (showString "@"), prt 11 exp])
