-- File generated by the BNF Converter (bnfc 2.9.5).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module Syntax.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified Syntax.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transNumber :: Syntax.Abs.Number -> Result
transNumber x = case x of
  Syntax.Abs.Number string -> failure x

transChr :: Syntax.Abs.Chr -> Result
transChr x = case x of
  Syntax.Abs.Chr string -> failure x

transStr :: Syntax.Abs.Str -> Result
transStr x = case x of
  Syntax.Abs.Str string -> failure x

transHole :: Syntax.Abs.Hole -> Result
transHole x = case x of
  Syntax.Abs.Hole string -> failure x

transId :: Syntax.Abs.Id -> Result
transId x = case x of
  Syntax.Abs.Id string -> failure x

transRepl :: Show a => Syntax.Abs.Repl' a -> Result
transRepl x = case x of
  Syntax.Abs.LetR _ decs -> failure x
  Syntax.Abs.ExpR _ exp -> failure x
  Syntax.Abs.RequireR _ str -> failure x

transDec :: Show a => Syntax.Abs.Dec' a -> Result
transDec x = case x of
  Syntax.Abs.StructureD _ structurekwd rule -> failure x
  Syntax.Abs.ConstantD _ rule -> failure x
  Syntax.Abs.ProofD _ proofsteps -> failure x
  Syntax.Abs.DeclarationD _ patterns -> failure x
  Syntax.Abs.PipeClauseD _ pipeclause -> failure x

transStructureKwd :: Show a => Syntax.Abs.StructureKwd' a -> Result
transStructureKwd x = case x of
  Syntax.Abs.DataKwd _ -> failure x
  Syntax.Abs.RecordKwd _ -> failure x
  Syntax.Abs.ModuleKwd _ -> failure x
  Syntax.Abs.ClassKwd _ -> failure x
  Syntax.Abs.InstanceKwd _ -> failure x
  Syntax.Abs.AxiomKwd _ -> failure x
  Syntax.Abs.TheoremKwd _ -> failure x

transRule :: Show a => Syntax.Abs.Rule' a -> Result
transRule x = case x of
  Syntax.Abs.ByBlockR _ pat proofsteps -> failure x
  Syntax.Abs.ProofR _ pat proofsteps -> failure x
  Syntax.Abs.ValueR _ pat exp -> failure x
  Syntax.Abs.WhereR _ pat decs -> failure x
  Syntax.Abs.SigR _ pat -> failure x

transProofStep :: Show a => Syntax.Abs.ProofStep' a -> Result
transProofStep x = case x of
  Syntax.Abs.ProofDecPS _ proofdec -> failure x
  Syntax.Abs.BulletBlockPS _ proofsteps -> failure x
  Syntax.Abs.CasesPS _ exps -> failure x
  Syntax.Abs.CasesWithPS _ exps -> failure x
  Syntax.Abs.InductionPS _ exps -> failure x
  Syntax.Abs.PipeClausePS _ pipeclause -> failure x
  Syntax.Abs.ProvingPS _ exp -> failure x
  Syntax.Abs.ApplyPS _ exp exps -> failure x
  Syntax.Abs.InstantiatePS _ exp -> failure x
  Syntax.Abs.IntroPS _ patterns -> failure x
  Syntax.Abs.WitnessPS _ expopt -> failure x
  Syntax.Abs.ExpPS _ exp -> failure x

transProofDec :: Show a => Syntax.Abs.ProofDec' a -> Result
transProofDec x = case x of
  Syntax.Abs.AssumePD _ patterns -> failure x
  Syntax.Abs.ByContradictionPD _ pat typeannopt -> failure x
  Syntax.Abs.LetPD _ decs -> failure x
  Syntax.Abs.LemmaPD _ rule -> failure x
  Syntax.Abs.OpenPD _ id -> failure x
  Syntax.Abs.PickAnyPD _ patterns -> failure x
  Syntax.Abs.PickWitnessPD _ patterns exp -> failure x
  Syntax.Abs.ChainingPD _ chainlinks -> failure x
  Syntax.Abs.RewritePD _ rewriteitems -> failure x
  Syntax.Abs.UnfoldPD _ pats -> failure x

transChainLink :: Show a => Syntax.Abs.ChainLink' a -> Result
transChainLink x = case x of
  Syntax.Abs.EasyCL _ chainop exp -> failure x
  Syntax.Abs.ByCL _ chainop exp proofsteps -> failure x

transChainOp :: Show a => Syntax.Abs.ChainOp' a -> Result
transChainOp x = case x of
  Syntax.Abs.LeftLongArrowCO _ -> failure x
  Syntax.Abs.LeftArrowCO _ -> failure x
  Syntax.Abs.RightLongArrowCO _ -> failure x
  Syntax.Abs.RightArrowCO _ -> failure x
  Syntax.Abs.EqCO _ -> failure x
  Syntax.Abs.EqualCO _ -> failure x
  Syntax.Abs.EquivCO _ -> failure x
  Syntax.Abs.ExpCO _ exp -> failure x

transRewriteItem :: Show a => Syntax.Abs.RewriteItem' a -> Result
transRewriteItem x = case x of
  Syntax.Abs.MkRI _ directionopt exp -> failure x

transDirectionOpt :: Show a => Syntax.Abs.DirectionOpt' a -> Result
transDirectionOpt x = case x of
  Syntax.Abs.LeftDO _ -> failure x
  Syntax.Abs.RightDO _ -> failure x
  Syntax.Abs.NoDO _ -> failure x

transPatterns :: Show a => Syntax.Abs.Patterns' a -> Result
transPatterns x = case x of
  Syntax.Abs.MkP _ params typeannopt -> failure x

transParam :: Show a => Syntax.Abs.Param' a -> Result
transParam x = case x of
  Syntax.Abs.BareP _ pat -> failure x
  Syntax.Abs.ExplicitP _ pat -> failure x
  Syntax.Abs.InvisibleP _ pat -> failure x

transPat :: Show a => Syntax.Abs.Pat' a -> Result
transPat x = case x of
  Syntax.Abs.NoncomputableP _ pat -> failure x
  Syntax.Abs.TypeP _ pat -> failure x
  Syntax.Abs.PropP _ pat -> failure x
  Syntax.Abs.CtorAnnP _ pat exps -> failure x
  Syntax.Abs.SuperAnnP _ pat exps -> failure x
  Syntax.Abs.SubAnnP _ pat exps -> failure x
  Syntax.Abs.AnnP _ pat exp -> failure x
  Syntax.Abs.OrP _ pat1 pat2 -> failure x
  Syntax.Abs.AndP _ pat1 pat2 -> failure x
  Syntax.Abs.IndP _ pat -> failure x
  Syntax.Abs.CallP _ pat param params -> failure x
  Syntax.Abs.NumberP _ number -> failure x
  Syntax.Abs.CharP _ chr -> failure x
  Syntax.Abs.StringP _ str -> failure x
  Syntax.Abs.HoleP _ hole -> failure x
  Syntax.Abs.VarP _ id -> failure x
  Syntax.Abs.RecordP _ fieldpats -> failure x
  Syntax.Abs.TupleP _ pat pats -> failure x
  Syntax.Abs.UnitP _ -> failure x
  Syntax.Abs.WitnessP _ pat1 pat2 -> failure x

transFieldPat :: Show a => Syntax.Abs.FieldPat' a -> Result
transFieldPat x = case x of
  Syntax.Abs.PunP _ id -> failure x
  Syntax.Abs.FieldP _ id pat -> failure x

transTypeAnnOpt :: Show a => Syntax.Abs.TypeAnnOpt' a -> Result
transTypeAnnOpt x = case x of
  Syntax.Abs.HasTAO _ exp -> failure x
  Syntax.Abs.NoTAO _ -> failure x

transExpOpt :: Show a => Syntax.Abs.ExpOpt' a -> Result
transExpOpt x = case x of
  Syntax.Abs.HasEO _ exp -> failure x
  Syntax.Abs.NoEO _ -> failure x

transExp :: Show a => Syntax.Abs.Exp' a -> Result
transExp x = case x of
  Syntax.Abs.EqE _ exp1 exp2 -> failure x
  Syntax.Abs.ApplyE _ exp -> failure x
  Syntax.Abs.ProofDecInE _ proofdec exp -> failure x
  Syntax.Abs.WitnessSuchThatE _ exps exp -> failure x
  Syntax.Abs.AnnE _ exp1 exp2 -> failure x
  Syntax.Abs.FunE _ params exp -> failure x
  Syntax.Abs.ProvingByE _ expopt proofsteps -> failure x
  Syntax.Abs.SufficesByE _ exp proofsteps -> failure x
  Syntax.Abs.ExistsE _ patterns exp -> failure x
  Syntax.Abs.ForallE _ patterns exp -> failure x
  Syntax.Abs.ArrowE _ exp1 exp2 -> failure x
  Syntax.Abs.ImplicationE _ exp1 exp2 -> failure x
  Syntax.Abs.EquivalenceE _ exp1 exp2 -> failure x
  Syntax.Abs.DisjunctionE _ exp1 exp2 -> failure x
  Syntax.Abs.ConjunctionE _ exp1 exp2 -> failure x
  Syntax.Abs.NegationE _ exp -> failure x
  Syntax.Abs.EqualE _ exp1 exp2 -> failure x
  Syntax.Abs.CallE _ exp args -> failure x
  Syntax.Abs.ExplicitE _ id -> failure x
  Syntax.Abs.LamCasesE _ patterns clauses -> failure x
  Syntax.Abs.CaseE _ exp clauses -> failure x
  Syntax.Abs.MatchWith _ exp pipeclauses -> failure x
  Syntax.Abs.InstantiateWithE _ exp -> failure x
  Syntax.Abs.UnitE _ -> failure x
  Syntax.Abs.TupleE _ exp exps -> failure x
  Syntax.Abs.RecordE _ decs -> failure x
  Syntax.Abs.RecordUpdateE _ exp decs -> failure x
  Syntax.Abs.AssumptionE _ -> failure x
  Syntax.Abs.NumberE _ number -> failure x
  Syntax.Abs.CharE _ chr -> failure x
  Syntax.Abs.StringE _ str -> failure x
  Syntax.Abs.HoleE _ hole -> failure x
  Syntax.Abs.VarE _ id -> failure x

transClause :: Show a => Syntax.Abs.Clause' a -> Result
transClause x = case x of
  Syntax.Abs.MkC _ params exp -> failure x

transPipeClause :: Show a => Syntax.Abs.PipeClause' a -> Result
transPipeClause x = case x of
  Syntax.Abs.MkPC _ pats proofsteps -> failure x

transArg :: Show a => Syntax.Abs.Arg' a -> Result
transArg x = case x of
  Syntax.Abs.BareA _ exp -> failure x
  Syntax.Abs.ExplicitA _ exp -> failure x
