-- File generated by the BNF Converter (bnfc 2.9.5).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module Syntax.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified Syntax.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transNumber :: Syntax.Abs.Number -> Result
transNumber x = case x of
  Syntax.Abs.Number string -> failure x

transChr :: Syntax.Abs.Chr -> Result
transChr x = case x of
  Syntax.Abs.Chr string -> failure x

transStr :: Syntax.Abs.Str -> Result
transStr x = case x of
  Syntax.Abs.Str string -> failure x

transHole :: Syntax.Abs.Hole -> Result
transHole x = case x of
  Syntax.Abs.Hole string -> failure x

transId :: Syntax.Abs.Id -> Result
transId x = case x of
  Syntax.Abs.Id string -> failure x

transRepl :: Syntax.Abs.Repl -> Result
transRepl x = case x of
  Syntax.Abs.LetR decs -> failure x
  Syntax.Abs.ExpR exp -> failure x
  Syntax.Abs.RequireR str -> failure x

transDec :: Syntax.Abs.Dec -> Result
transDec x = case x of
  Syntax.Abs.StructureD structurekwd rule -> failure x
  Syntax.Abs.ConstantD rule -> failure x
  Syntax.Abs.ProofD proofsteps -> failure x
  Syntax.Abs.DeclarationD patterns -> failure x
  Syntax.Abs.PipeClauseD pipeclause -> failure x

transStructureKwd :: Syntax.Abs.StructureKwd -> Result
transStructureKwd x = case x of
  Syntax.Abs.DataKwd -> failure x
  Syntax.Abs.RecordKwd -> failure x
  Syntax.Abs.ModuleKwd -> failure x
  Syntax.Abs.ClassKwd -> failure x
  Syntax.Abs.InstanceKwd -> failure x
  Syntax.Abs.AxiomKwd -> failure x
  Syntax.Abs.TheoremKwd -> failure x

transRule :: Syntax.Abs.Rule -> Result
transRule x = case x of
  Syntax.Abs.ByBlockR pat proofsteps -> failure x
  Syntax.Abs.ProofR pat proofsteps -> failure x
  Syntax.Abs.ValueR pat exp -> failure x
  Syntax.Abs.WhereR pat decs -> failure x
  Syntax.Abs.SigR pat -> failure x

transProofStep :: Syntax.Abs.ProofStep -> Result
transProofStep x = case x of
  Syntax.Abs.ProofDecPS proofdec -> failure x
  Syntax.Abs.BulletBlockPS proofsteps -> failure x
  Syntax.Abs.CasesPS exps -> failure x
  Syntax.Abs.CasesWithPS exps -> failure x
  Syntax.Abs.InductionPS exps -> failure x
  Syntax.Abs.PipeClausePS pipeclause -> failure x
  Syntax.Abs.ProvingPS exp -> failure x
  Syntax.Abs.ApplyPS exp exps -> failure x
  Syntax.Abs.InstantiatePS exp -> failure x
  Syntax.Abs.IntroPS patterns -> failure x
  Syntax.Abs.WitnessPS expopt -> failure x
  Syntax.Abs.ExpPS exp -> failure x

transProofDec :: Syntax.Abs.ProofDec -> Result
transProofDec x = case x of
  Syntax.Abs.AssumePD patterns -> failure x
  Syntax.Abs.ByContradictionPD pat annopt -> failure x
  Syntax.Abs.LetPD decs -> failure x
  Syntax.Abs.LemmaPD rule -> failure x
  Syntax.Abs.OpenPD id -> failure x
  Syntax.Abs.PickAnyPD patterns -> failure x
  Syntax.Abs.PickWitnessPD patterns exp -> failure x
  Syntax.Abs.ChainingPD chainlinks -> failure x
  Syntax.Abs.RewritePD rewriteitems -> failure x
  Syntax.Abs.UnfoldPD pats -> failure x

transChainLink :: Syntax.Abs.ChainLink -> Result
transChainLink x = case x of
  Syntax.Abs.EasyCL chainop exp -> failure x
  Syntax.Abs.ByCL chainop exp proofsteps -> failure x

transChainOp :: Syntax.Abs.ChainOp -> Result
transChainOp x = case x of
  Syntax.Abs.LeftLongArrowCO -> failure x
  Syntax.Abs.LeftArrowCO -> failure x
  Syntax.Abs.RightLongArrowCO -> failure x
  Syntax.Abs.RightArrowCO -> failure x
  Syntax.Abs.EqCO -> failure x
  Syntax.Abs.EqualCO -> failure x
  Syntax.Abs.EquivCO -> failure x
  Syntax.Abs.ExpCO exp -> failure x

transRewriteItem :: Syntax.Abs.RewriteItem -> Result
transRewriteItem x = case x of
  Syntax.Abs.MkRI directionopt exp -> failure x

transDirectionOpt :: Syntax.Abs.DirectionOpt -> Result
transDirectionOpt x = case x of
  Syntax.Abs.LeftDO -> failure x
  Syntax.Abs.RightDO -> failure x
  Syntax.Abs.NoDO -> failure x

transPatterns :: Syntax.Abs.Patterns -> Result
transPatterns x = case x of
  Syntax.Abs.MkP params annopt -> failure x

transParam :: Syntax.Abs.Param -> Result
transParam x = case x of
  Syntax.Abs.BareP pat -> failure x
  Syntax.Abs.AtP pat -> failure x
  Syntax.Abs.HashP pat -> failure x

transPat :: Syntax.Abs.Pat -> Result
transPat x = case x of
  Syntax.Abs.NoncomputableP pat -> failure x
  Syntax.Abs.TypeP pat -> failure x
  Syntax.Abs.PropP pat -> failure x
  Syntax.Abs.CtorAnnP pat exps -> failure x
  Syntax.Abs.SuperAnnP pat exps -> failure x
  Syntax.Abs.SubAnnP pat exps -> failure x
  Syntax.Abs.AnnP pat exp -> failure x
  Syntax.Abs.OrP pat1 pat2 -> failure x
  Syntax.Abs.AndP pat1 pat2 -> failure x
  Syntax.Abs.IndP pat -> failure x
  Syntax.Abs.CallP pat param params -> failure x
  Syntax.Abs.NumberP number -> failure x
  Syntax.Abs.CharP chr -> failure x
  Syntax.Abs.StringP str -> failure x
  Syntax.Abs.HoleP hole -> failure x
  Syntax.Abs.VarP id -> failure x
  Syntax.Abs.RecordP fieldpats -> failure x
  Syntax.Abs.TupleP pat pats -> failure x
  Syntax.Abs.UnitP -> failure x
  Syntax.Abs.WitnessP pat1 pat2 -> failure x

transFieldPat :: Syntax.Abs.FieldPat -> Result
transFieldPat x = case x of
  Syntax.Abs.PunP id -> failure x
  Syntax.Abs.FieldP id pat -> failure x

transAnnOpt :: Syntax.Abs.AnnOpt -> Result
transAnnOpt x = case x of
  Syntax.Abs.HasAnn exp -> failure x
  Syntax.Abs.NoAnn -> failure x

transExpOpt :: Syntax.Abs.ExpOpt -> Result
transExpOpt x = case x of
  Syntax.Abs.HasExp exp -> failure x
  Syntax.Abs.NoExp -> failure x

transExp :: Syntax.Abs.Exp -> Result
transExp x = case x of
  Syntax.Abs.EqE exp1 exp2 -> failure x
  Syntax.Abs.ApplyE exp -> failure x
  Syntax.Abs.ProofDecInE proofdec exp -> failure x
  Syntax.Abs.WitnessSuchThatE exps exp -> failure x
  Syntax.Abs.AnnE exp1 exp2 -> failure x
  Syntax.Abs.FunE params exp -> failure x
  Syntax.Abs.ProvingByE expopt proofsteps -> failure x
  Syntax.Abs.SufficesByE exp proofsteps -> failure x
  Syntax.Abs.ExistsE patterns exp -> failure x
  Syntax.Abs.ForallE patterns exp -> failure x
  Syntax.Abs.ArrowE exp1 exp2 -> failure x
  Syntax.Abs.ImplicationE exp1 exp2 -> failure x
  Syntax.Abs.EquivalenceE exp1 exp2 -> failure x
  Syntax.Abs.DisjunctionE exp1 exp2 -> failure x
  Syntax.Abs.ConjunctionE exp1 exp2 -> failure x
  Syntax.Abs.NegationE exp -> failure x
  Syntax.Abs.EqualE exp1 exp2 -> failure x
  Syntax.Abs.CallE exp args -> failure x
  Syntax.Abs.ExplicitE id -> failure x
  Syntax.Abs.LamCasesE patterns clauses -> failure x
  Syntax.Abs.CaseE exp clauses -> failure x
  Syntax.Abs.MatchWith exp pipeclauses -> failure x
  Syntax.Abs.InstantiateWithE exp -> failure x
  Syntax.Abs.UnitE -> failure x
  Syntax.Abs.TupleE exp exps -> failure x
  Syntax.Abs.RecordE decs -> failure x
  Syntax.Abs.RecordUpdateE exp decs -> failure x
  Syntax.Abs.AssumptionE -> failure x
  Syntax.Abs.NumberE number -> failure x
  Syntax.Abs.CharE chr -> failure x
  Syntax.Abs.StringE str -> failure x
  Syntax.Abs.HoleE hole -> failure x
  Syntax.Abs.VarE id -> failure x

transClause :: Syntax.Abs.Clause -> Result
transClause x = case x of
  Syntax.Abs.MkC params exp -> failure x

transPipeClause :: Syntax.Abs.PipeClause -> Result
transPipeClause x = case x of
  Syntax.Abs.MkPC pats proofsteps -> failure x

transArg :: Syntax.Abs.Arg -> Result
transArg x = case x of
  Syntax.Abs.BareA exp -> failure x
  Syntax.Abs.AtA exp -> failure x
